Новое правило зеленых зон, исправил ошибки
plasmoapp/plasmo-rp-wiki pull request #5
Opened 2022-05-01 14:09 UTC by howkawgew

ААААА КОМАР

2022-05-01 14:58 UTC, rsmanito requested changes
хокаге ты безграмотный

2022-05-01 14:58 UTC, rsmanito commented on pages/bedrock.md
> +После того как вы зайдете, вас попросит нажать на ссылку в чате, чтобы авторизоваться
После того как вы зайдете, Вас попросит нажать на ссылку в чате для авторизации

2022-05-01 14:58 UTC, rsmanito commented on pages/commune.md
> +Альбом со скриншотами — это главное, что может заинтересовать игрока, который хочет вступить в вашу общину. Постарайтесь над ним. Если у вашей общины ещё нет построек, то возможно стоит хоть что-то п
Альбом со скриншотами — это главное, что может заинтересовать игрока, который хочет вступить в вашу общину. Постарайтесь над ним. Если у Вашей общины ещё нет построек, то, возможно, стоит хоть что-то построить, прежде чем создавать общину

2022-05-01 14:58 UTC, rsmanito commented on pages/commune.md
> +Это пригодится, чтобы запретить писать в чаты пользователям, которые не играют на сервере. Проще узнавать игроков с никами, одинаковыми как в Discord, так и в игре
Это пригодится, чтобы запретить писать в чаты пользователям, которые не играют на сервере. Проще узнавать игроков с никами, которые совпадают с игровыми

2022-05-01 14:58 UTC, rsmanito commented on pages/commune.md
> +#### ⚠ Сейчас мы испытываем небольшие технические трудности с добавлением бота на новые сервера, как только мы всё починим - сделаем анонс в канале #объявления в нашем Discord сервере
⚠

2022-05-01 14:58 UTC, rsmanito commented on pages/commune.md
> +3. Создайте роли, которые будет синхронизировать бот. Их можно назвать как угодно, поставить любой цвет и любые права. Если вы не хотите синхронизировать роли, то можете пропустить этот пункт. Необяз
3. Создайте роли, которые будет синхронизировать бот. Их можно назвать как угодно, поставить любой цвет и любые права. Если Вы не хотите синхронизировать роли, то можете пропустить этот пункт. Не обязательно синхронизировать все роли, можно синхронизировать только нужные

2022-05-01 14:58 UTC, rsmanito commented on pages/commune.md
> +Повторите это для всех ролей, или не повторяйте, указывать все роли необязательно
Повторите это для всех нужных ролей. Указывать все роли необязательно

2022-05-01 14:58 UTC, rsmanito commented on pages/creative.md
> +`/secretblocks`, `/blocks` — Меню с блоками, которые нельзя найти в творческом инвентаре. Барьер, яйцо дракона, дебаг-палку и спавнер
Меню с блоками, которые нельзя найти в творческом инвентаре: барьер, яйцо дракона, дебаг-палка и спавнер

2022-05-01 14:58 UTC, rsmanito commented on pages/mko.md
> +Строит и развивает общие проекты. Хаб в аду, основной остров в энде, ветки, спавн или общие фермы. Глава Инфраструктуры назначает людей для разных задач, например отдельного игрока, который следит за
Строит и развивает общие проекты. Хаб в аду, основной остров в энде, ветки, спавн или общие фермы. Глава Инфраструктуры назначает людей для разных задач, например: отдельного игрока, который следит за порядком в энде, или целый отряд, следящий за ветками в аду

2022-05-01 14:58 UTC, rsmanito commented on pages/resources.md
> +Ресурспак опциональный, устаналивать его необязательно. Но он добавляет много крутых фич, поэтому мы рекомендуем играть с этим ресурспаком
Ресурспак опциональный, устанавливать его не обязательно. Но он добавляет много крутых фич, поэтому мы рекомендуем играть с этим ресурспаком

2022-05-01 14:58 UTC, rsmanito commented on pages/rules.md
> +- Не используйте блоки для того, чтобы перемещаться, или, чтобы забираться на гору
- Не используйте блоки для перемещения, или, чтобы забираться на гору

2022-05-01 14:58 UTC, rsmanito commented on pages/rules.md
> +Но вы не можете использовать его, чтобы искать спавнеры и руды
Но вы не можете использовать его для поиска спавнеров и руд

2022-05-01 14:58 UTC, rsmanito commented on pages/rules.md
> +То же самое с картами. Запрещено использовать моды на мини-карту, чтобы искать пещеры и шахты. Запрещено использовать карты, которые показывают энтити или игроков
То же самое с картами. Запрещено использовать моды на мини-карту с включенным режимом пещер. Запрещено использовать карты, которые показывают энтити или игроков

2022-05-01 14:58 UTC, rsmanito commented on pages/rules.md
> +Если вы хотите занять территорию, и в радиусе 300 блоков есть уже занятая территория — вы должны договорится с владельцем, и заключить контракт, в котором он подтвердит, что он не против. В противном
Если вы хотите занять территорию и в радиусе 300 блоков есть уже занятая территория — Вы должны договорится с владельцем, и заключить контракт, в котором он подтвердит, что он не против. В противном случае он сможет подать на Вас в суд

2022-05-02 13:10 UTC, KPidS commented
@howkawgew Чекни, что там Манито высрал, мне лень разбираться и проверять

2022-05-02 22:11 UTC, howkawgew commented on pages/resources.md
> +Ресурспак опциональный, устаналивать его необязательно. Но он добавляет много крутых фич, поэтому мы рекомендуем играть с этим ресурспаком
С чего ты решил что там раздельно "необязательно" пишется? Обычно пишется слитно с "не", отсутствует противопоставление

2022-05-02 22:12 UTC, howkawgew commented on pages/commune.md
> +Альбом со скриншотами — это главное, что может заинтересовать игрока, который хочет вступить в вашу общину. Постарайтесь над ним. Если у вашей общины ещё нет построек, то возможно стоит хоть что-то п
почему ты заменяешь некоторые вы на Вы, но не заменяешь другие? Изменение всех вы на Вы это уже к другому пуллреквесту, можешь создать сам или я создам позже

2022-05-02 22:12 UTC, howkawgew commented on pages/bedrock.md
> +После того как вы зайдете, вас попросит нажать на ссылку в чате, чтобы авторизоваться
Изменение всех вы на Вы это уже к другому пуллреквесту, можешь создать сам или я создам позже

2022-05-02 22:14 UTC, howkawgew commented on pages/commune.md
> +3. Создайте роли, которые будет синхронизировать бот. Их можно назвать как угодно, поставить любой цвет и любые права. Если вы не хотите синхронизировать роли, то можете пропустить этот пункт. Необяз
Вы - дело отдельного PR. Необязательно пишется слитно

2022-05-02 22:16 UTC, howkawgew commented on pages/rules.md
> +Но вы не можете использовать его, чтобы искать спавнеры и руды
Это слож­но­под­чи­нен­ное пред­ло­же­ние, в кото­ром при­да­точ­ное цели при­со­еди­ня­ет­ся к глав­но­му пред­ло­же­нию с помо­щью сло­ва слу­жеб­ной части речи — "чтобы"

2022-05-02 22:19 UTC, howkawgew commented on pages/rules.md
> +Если вы хотите занять территорию, и в радиусе 300 блоков есть уже занятая территория — вы должны договорится с владельцем, и заключить контракт, в котором он подтвердит, что он не против. В противном
Вы - отдельный PR.
"Вы - хотите" и "есть территория" - это сложное предложение, запятая ставится обязательно, даже при условии что там есть "И"

2022-05-02 22:21 UTC, howkawgew commented on pages/rules.md
> +То же самое с картами. Запрещено использовать моды на мини-карту, чтобы искать пещеры и шахты. Запрещено использовать карты, которые показывают энтити или игроков
чТо ТаКоЕ рЕжИм пЕщЕр. Не заставляй читателя думать о том что такое режим пещер, "чтобы искать пещеры и шахты" - звучит понятнее

2022-05-02 22:23 UTC, howkawgew commented on pages/rules.md
> +Если вы хотите занять территорию, и в радиусе 300 блоков есть уже занятая территория — вы должны договорится с владельцем, и заключить контракт, в котором он подтвердит, что он не против. В противном
А вот перед "и заключить контракт" ничего стоять не должно, щас пофикшу

2022-05-02 22:26 UTC, howkawgew commented on pages/rules.md
> +- Не используйте блоки для того, чтобы перемещаться, или, чтобы забираться на гору
Исправил

2022-05-02 22:27 UTC, howkawgew commented on pages/mko.md
> +Строит и развивает общие проекты. Хаб в аду, основной остров в энде, ветки, спавн или общие фермы. Глава Инфраструктуры назначает людей для разных задач, например отдельного игрока, который следит за
Бред

2022-05-02 22:29 UTC, howkawgew commented on pages/commune.md
> +Повторите это для всех ролей, или не повторяйте, указывать все роли необязательно
Нарушаешь стиль, слишком формально

2022-05-02 22:38 UTC, howkawgew commented on pages/creative.md
> +`/secretblocks`, `/blocks` — Меню с блоками, которые нельзя найти в творческом инвентаре. Барьер, яйцо дракона, дебаг-палку и спавнер
за "палка" спасибо, двоеточие useless

2022-05-02 22:40 UTC, howkawgew commented on pages/commune.md
> +Это пригодится, чтобы запретить писать в чаты пользователям, которые не играют на сервере. Проще узнавать игроков с никами, одинаковыми как в Discord, так и в игре
Переделал, Это пригодится, чтобы запретить писать тем, кто не играет на сервере. Проще узнавать игроков, если их ники синхронизированы с игрой

2022-05-02 22:41 UTC, howkawgew commented
@KPidS Исправил

2022-05-05 19:56 UTC, howkawgew commented
ало блядота

2022-05-06 05:58 UTC, rsmanito commented
сойдет

2022-07-06 05:54 UTC, howkawgew commented
### 4

2022-08-21 16:53 UTC, closed without merging